/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package quant-trading/android */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "bridge.go"

#include <jni.h>
#include <stdlib.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <android/log.h>
#include <sys/mman.h>
#include <elf.h>
#include <sys/syscall.h>
#include <fcntl.h>
#include <dlfcn.h>

#define LOG_TAG "QuantGo"

static void _go_log(int prio, const char *msg) {
    __android_log_write(prio, LOG_TAG, msg);
}

// ---- VDSO workaround: SIGSEGV handler that emulates clock_gettime ----

static char vdso_handler_buf[1024];
static unsigned long vdso_page_start;
static unsigned long vdso_page_end;

// Raw syscall for clock_gettime (bypasses VDSO/libc entirely).
static long raw_clock_gettime(clockid_t clk_id, struct timespec *tp) {
    return syscall(SYS_clock_gettime, clk_id, tp);
}

static void vdso_sigsegv_handler(int signo, siginfo_t *info, void *ucontext) {
    if ((uintptr_t)info->si_addr >= vdso_page_start &&
        (uintptr_t)info->si_addr < vdso_page_end &&
        vdso_page_start != 0) {
        // VDSO crash - emulate clock_gettime via raw syscall
        ucontext_t *uc = (ucontext_t *)ucontext;
        clockid_t clk_id = (clockid_t)uc->uc_mcontext.regs[0];
        struct timespec *tp = (struct timespec *)uc->uc_mcontext.sp;
        raw_clock_gettime(clk_id, tp);
        uc->uc_mcontext.pc = uc->uc_mcontext.regs[30]; // skip to LR (return addr)
        return;
    }
    // Non-VDSO crash: write to log and terminate
    FILE *crf = fopen("/data/data/com.liangzai.quant/files/quant/native_crash.log", "a");
    if (crf) {
        fprintf(crf, "[%ld] NATIVE CRASH signal=%d addr=%p\n",
                (long)time(0), signo, info->si_addr);
        fclose(crf);
    }
    signal(signo, SIG_DFL);
    raise(signo);
}

static void install_vdso_handler(void) {
    // Find VDSO page range
    unsigned long vdso = 0;
    unsigned long buf[2];
    FILE *f = fopen("/proc/self/auxv", "rb");
    if (f) {
        while (fread(buf, sizeof(buf), 1, f) == 1) {
            if (buf[0] == AT_SYSINFO_EHDR) { vdso = buf[1]; break; }
            if (buf[0] == AT_NULL) break;
        }
        fclose(f);
    }
    if (!vdso || vdso < 0x1000) return;
    vdso_page_start = vdso & ~(unsigned long)0xfff;
    vdso_page_end = vdso_page_start + 0x2000; // VDSO typically < 2 pages

    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = vdso_sigsegv_handler;
    sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
    sigaltstack(&((stack_t){.ss_sp = vdso_handler_buf, .ss_size = sizeof(vdso_handler_buf)}), NULL);
    sigaction(SIGSEGV, &sa, NULL);
}

__attribute__((constructor))
static void _init_vdso_fix(void) {
    install_vdso_handler();
}

static void crash_handler(int sig) {
    FILE *f = fopen("/data/data/com.liangzai.quant/files/quant/native_crash.log", "a");
    if (f) {
        time_t now = time(0);
        struct tm *tm = localtime(&now);
        fprintf(f, "[%04d-%02d-%02d %02d:%02d:%02d] CRASH sig=%d\n",
                1900+tm->tm_year, tm->tm_mon+1, tm->tm_mday,
                tm->tm_hour, tm->tm_min, tm->tm_sec, sig);
        fclose(f);
    }
    signal(sig, SIG_DFL);
    raise(sig);
}

static void install_handlers(void) {
    signal(SIGABRT, crash_handler);
    signal(SIGBUS, crash_handler);
    signal(SIGILL, crash_handler);
    signal(SIGFPE, crash_handler);
    // SIGSEGV handled by vdso_sigsegv_handler
}

static int check_tracer_pid() {
    char buf[256];
    FILE *f = fopen("/proc/self/status", "r");
    if (!f) return 0;
    while (fgets(buf, sizeof(buf), f)) {
        if (strncmp(buf, "TracerPid:", 10) == 0) {
            int pid = 0;
            sscanf(buf + 10, "%d", &pid);
            fclose(f);
            return pid != 0;
        }
    }
    fclose(f);
    return 0;
}

static int check_debug_flags() {
    if (check_tracer_pid()) return 1;
    // detect ptrace by trying to attach to self
    int fd = open("/proc/self/status", O_RDONLY);
    if (fd < 0) return 1;
    close(fd);
    return 0;
}

// simple integrity: compare a checksum from .so load address
static unsigned long compute_self_hash(void) {
    Dl_info info;
    unsigned long hash = 0;
    if (dladdr((void*)compute_self_hash, &info)) {
        unsigned long *p = (unsigned long*)info.dli_fbase;
        for (int i = 0; i < 64; i++) {
            hash ^= p[i] ^ (hash << 5) ^ (hash >> 3);
        }
    }
    return hash;
}

static jstring strToJString(JNIEnv *env, const char* str) {
    return (*env)->NewStringUTF(env, str);
}

static int getJavaVM(JNIEnv *env, JavaVM **vm) {
    return (*env)->GetJavaVM(env, vm);
}

static jclass findClass(JNIEnv *env, const char *name) {
    return (*env)->FindClass(env, name);
}

static jmethodID getStaticMethodID(JNIEnv *env, jclass cls, const char *name, const char *sig) {
    return (*env)->GetStaticMethodID(env, cls, name, sig);
}

static void callStaticVoidMethod(JNIEnv *env, jclass cls, jmethodID mid, jstring arg1, jstring arg2) {
    (*env)->CallStaticVoidMethod(env, cls, mid, arg1, arg2);
}

static jobject newGlobalRef(JNIEnv *env, jobject obj) {
    return (*env)->NewGlobalRef(env, obj);
}

static void deleteLocalRef(JNIEnv *env, jobject obj) {
    (*env)->DeleteLocalRef(env, obj);
}

static const char* jstring_to_c(JNIEnv *env, jstring s) {
    if (!s) return NULL;
    return (*env)->GetStringUTFChars(env, s, NULL);
}

static void jstring_free(JNIEnv *env, jstring s, const char *cstr) {
    if (cstr) (*env)->ReleaseStringUTFChars(env, s, cstr);
}

static int attachThread(JavaVM *vm, JNIEnv **env) {
    return (*vm)->AttachCurrentThread(vm, env, NULL);
}

static int detachThread(JavaVM *vm) {
    return (*vm)->DetachCurrentThread(vm);
}

static void warmup_vdso(void) {
    unsigned long vdso = 0;
    FILE *f = fopen("/proc/self/auxv", "rb");
    if (f) {
        unsigned long key, val;
        while (fread(&key, sizeof(key), 1, f) == 1 &&
               fread(&val, sizeof(val), 1, f) == 1) {
            if (key == 33) {
                vdso = val;
                break;
            }
        }
        fclose(f);
    }
    if (!vdso) return;
    for (int i = 0; i < 4096; i += 64) {
        volatile char *p = (volatile char *)(vdso + i);
        (void)*p;
    }
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void Java_com_liangzai_quant_JNIBridge_startServer(JNIEnv* env, jobject cls, jstring configPathC, jstring listenAddrC);
extern void Java_com_liangzai_quant_JNIBridge_stopServer(void);

#ifdef __cplusplus
}
#endif
